#!/bin/sh
#
# @name UVify IFO
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
# @board intel_aerofc-v1 exclude
#
# @maintainer Hyon Lim <lim@uvify.com>
#

set VEHICLE_TYPE mc
set MIXER quad_x
set PWM_OUT 1234

# Increase this when material update happens and requires user update their parameter related to airframes.
set PARAM_DEFAULTS_VER 2

if [ $AUTOCNF = yes ]
then
	# Attitude & rate gains, Roll.
	param set MC_ROLL_P 6.5
	param set MC_ROLLRATE_P 0.15
	param set MC_ROLLRATE_I 0.2
	param set MC_ROLLRATE_D 0.0013

	# Pitch.
	param set MC_PITCH_P 6.5
	param set MC_PITCHRATE_P 0.15
	param set MC_PITCHRATE_I 0.2
	param set MC_PITCHRATE_D 0.0016

	# Yaw.
	param set MC_YAW_P 2.8
	param set MC_YAWRATE_P 0.2
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_D 0.0

	# We'd like to make sure this critical flight params to be constant. Not adjusted by other developers.
	param set MC_ROLLRATE_MAX 220.0
	param set MC_PITCHRATE_MAX 220.0
	param set MPC_MAN_TILT_MAX 35.0
	param set MC_YAWRATE_MAX 200.0
	param set MPC_MANTHR_MIN 0.08
	param set MPC_TILTMAX_AIR 45.0

	# Disable RC filtering.
	param set RC_FLT_CUTOFF 0.00000

	# Thrust curve (avoids the need for TPA)
	#param set THR_MDL_FAC 0.25

	# Board orientation.
	param set SENS_BOARD_ROT 10
	# Flow: Yaw 180.
	param set SENS_FLOW_ROT 4
	# TFMini on TEL3.
	param set SENS_TFMINI_CFG 103

	# EKF2.
	# Flow aid default on.
	param set EKF2_AID_MASK 3	
	param set EKF2_GND_EFF_DZ 6.0
	param set EKF2_HGT_MODE 1
	param set EKF2_MIN_RNG 0.3
	param set EKF2_RNG_AID 1

	# Flow.
	param set EKF2_OF_QMIN 70

	# Position control gains.
	param set MPC_Z_P 1.1
	param set MPC_Z_VEL_P 0.3
	param set MPC_Z_VEL_I 0.05
	param set MPC_Z_VEL_D 0.0

	param set MPC_THR_MIN 0.06
	param set MPC_THR_HOVER 0.44

	param set MIS_TAKEOFF_ALT 1.1
	param set MPC_XY_P 1.7
	param set MPC_XY_VEL_P 0.13
	param set MPC_XY_VEL_I 0.06
	param set MPC_XY_VEL_D 0.01
	param set MPC_TKO_RAMP_T 1.0
	param set MPC_TKO_SPEED 1.1
	param set MPC_VEL_MANUAL 3.0

	###############################
	# SMBus-based smart battery
	###############################
	# Enable batt_smbus.
	param set SENS_EN_BATT 1
	# UVify smart battery has 5.0x multiplier for both current and capacity.
	param set BAT_C_MULT   5.0

	###############################
	# Battery - analog fallback
	###############################
	# Current PX4's BAT{$i}_* params not working well, so I fallback to deprecated parameter set first.
	# set first battery source as internal.
	param set BAT_SOURCE 0
	# IFO-S is using 4 cells. This will be for analog fallback when smbus is not working.
	param set BAT_N_CELLS 4
	# IFO-S is using 4800 mAh pack.
	param set BAT_CAPACITY 4800
	# UVify Core internal ADC divider.
	param set BAT_V_DIV 10.14
	# UVify Core internal multiplier for shunt resistor for Amp.
	param set BAT_A_PER_V 18.18

	# Other params
	param set COM_ARM_EKF_AB 0.00500
	param set COM_DISARM_LAND 2

	# Filter settings
	param set IMU_GYRO_CUTOFF 90.00000

	# enable to use high-rate logging for better rate tracking analysis
	# default, EKF2, Debug, Computer Vision and Avoidance.
	param set SDLOG_PROFILE 163 
	# TELEM1 ttyS1 - Wifi module
	param set MAV_0_CONFIG 101
	param set MAV_0_RATE 0
	# onboard
	param set MAV_0_MODE 2
	param set SER_TEL1_BAUD 921600

	# TELEM2 ttyS2 - Sub 1-Ghz
	param set MAV_1_CONFIG 102
	# normal
	param set MAV_1_MODE 0
	param set SER_TEL2_BAUD 57600

	# DSHOT
	param set DSHOT_CONFIG 600

	# EKF OF POSITION
	param set EKF2_OF_POS_X 0.06
	param set EKF2_OF_POS_Y 0.03
	param set EKF2_OF_POS_Z -0.07

	# Failsafe
	param set COM_LOW_BAT_ACT 3
fi
